-- Domain entity ids are generated by the DEVICE and are deliberately meaningful:
-- 'sms:8393' (the provider message id, which is what makes re-ingesting the same
-- SMS idempotent), 'custom:fruits', 'uncategorized'. Declaring them UUID here
-- rejected every one of them and would have broken sync, not merely the initial
-- import.
--
-- Server-generated identities (users, devices, refresh tokens) stay UUID, as does
-- sync_ops.op_id, which the client generates as a real UUID for idempotency.

ALTER TABLE transaction_allocations DROP CONSTRAINT IF EXISTS transaction_allocations_transaction_id_fkey;

ALTER TABLE transactions              ALTER COLUMN id             TYPE TEXT USING id::text;
ALTER TABLE transaction_allocations   ALTER COLUMN id             TYPE TEXT USING id::text;
ALTER TABLE transaction_allocations   ALTER COLUMN transaction_id TYPE TEXT USING transaction_id::text;
ALTER TABLE categories                ALTER COLUMN id             TYPE TEXT USING id::text;
ALTER TABLE category_memory           ALTER COLUMN id             TYPE TEXT USING id::text;
ALTER TABLE budgets                   ALTER COLUMN id             TYPE TEXT USING id::text;
ALTER TABLE source_alerts             ALTER COLUMN id             TYPE TEXT USING id::text;
ALTER TABLE suggestions               ALTER COLUMN id             TYPE TEXT USING id::text;
ALTER TABLE sync_ops                  ALTER COLUMN entity_id      TYPE TEXT USING entity_id::text;

ALTER TABLE transaction_allocations
  ADD CONSTRAINT transaction_allocations_transaction_id_fkey
  FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE;
